name: Python package

on: [push]

jobs:
  build:
    runs-on: [Windows, macOS]
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ["3.12.0"]
        exclude:
          - os: macos-latest
            python-version: "3.12.0"
          - os: windows-latest
            python-version: "3.12.0"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.0'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}